# Generated by Django 3.2.3 on 2021-09-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20210909_0937'),
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.cliente'),
        ),
    ]
